# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for geoTransect.py

params:
    title: Test 
    basin: Windsor  # We should get this from the basins shapefile 
    id: 1
    description: This transect is the one we are using to test this module.
    extents:
        - 0
        - 40000
        - 2500
        - 0
    buffer: 3000
    data_dir: /Users/matt/Dropbox/geotransect_test/data
    feature_well: P-129
    curve_display: templates/Petrophysics_display_template.csv

data:
    transect_file: transects2Deliver/Transects.shp
    seismic_dir: seismic
    well_dir: wells
    elevation_file: elevation_raster/NS_DEM_ascii.asc
    bedrock_dir: bedrock
    striplog_dir: wells
    tops_file: wells/P-129/tops/P-129_tops.txt  # Need to make this dynamic, or just handle in well
