# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for geotransect.py

# Params are passed directly to the TransectContainer object, and all of the
# Containers it contains. So you have access to them everywhere. 
params:
    title: Transect 1 
    basin: Windsor  # We should get this from the basins shapefile 
    id: 1
    description: This transect is the one we are using to test this module. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    domain: depth  # Not currently used
    buffer: 300
    depth:
        - 0
        - 3000
    data_dir: data
    images_dir: images
    feature_well: # P-129
    seismic_log: GR  # Not currently used
    curve_display: templates/Petrophysics_display_template.csv

# Data strings are always interpreted as paths relative to data_dir in params.
# They are passed to specific data containers. If we need a specific GIS layer,
# then we want a filename. If we need a directory of data, then we want a dir.
# This interface should evolve with use.
data:
    transect_file: transects/Transects.shp
    seismic_dir: seismic
    well_dir: wells
    elevation_file: elevation/NS_DEM_ascii.asc
    bedrock_dir: bedrock
    potfield_dir: potfield
    basins_dir: basins  # Not currently used
    velocity_dir: velocity
    striplog_dir: wells
    tops_file: wells/P-129/tops/P-129_tops.txt  # Need to make this dynamic, or just handle in well

map:  # In layer order, top = first
    transects: transects/Transects.shp
    wells: wells/wells.shp
    seismic: seismic/seismic_lines.shp
    shade: elevation/DEM_slope.tif
    bedrock: bedrock/p00001gb.shp
